#' ChatGPT: Create Unit Tests
#'
#' Create `{testthat}` test cases for the code.
#'
#' @param code The code for which to create unit tests by ChatGPT.
#'
#' @examples
#' \dontrun{
#' cat(create_unit_tests("squared_numbers <- function(numbers) {\n  numbers ^ 2\n}"))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
create_unit_tests <- function(code) {
  prompt <- paste0(
    'Create a full testthat file, with test cases for the following R code: "', code, '"'
  )
  prompt <- paste0("Write a full testthat file for following R code: `", code, "`")
  # Get completions from ChatGPT
  response <- gpt_get_completions(prompt)

  # For each choice in the completions, split the code line by line
  to_cat <- sapply(response["choices"], \(x) {
    new = strsplit(x[["text"]], "\n")[[1]]
    old = strsplit(code, "\n")[[1]]

    # Identify which lines are new and recolor them
    recolor_ind <- which(!new %in% old)
    new[recolor_ind] <- cli::col_green(new[recolor_ind])
    paste(new, collapse = "\n")
  })

  # Create a string of the completions
  to_string <- sapply(response["choices"], \(x) {
    x[["text"]]
  })

  # print to console the colorized lines
  cat(cli::col_green("*** ChatGPT output:"), to_cat)

  # return the string itself
  invisible(to_string)
}
